##
def starting_position():   
    print("---------------------------------")
    print(f"Player 1")
    print("0                                ")
    print("_________________________________")
    print("                                0")
    print(f"                                Player 2")
    print("---------------------------------")
def P1_Hits_P2_Misses():
    print("---------------------------------")
    print(f"                              Player 1")
    print("                                0")
    print("_________________M________________")
    print("0                H               ")
    print(f"Player 2")
    print("---------------------------------")
def P2_Hits_P1_Misses():
    print("---------------------------------")
    print(f"                               Player 1")
    print("                                0")
    print("_________________H________________")
    print("0                M               ")
    print(f"Player 2")
    print("---------------------------------")
# Both Hit 3
def both_players_hit(): 
    print("---------------------------------")
    print(f"                               Player 1")
    print("                                0")
    print("_________________H________________")
    print("0                H               ")
    print(f"Player 2")
    print("---------------------------------")
def both_players__miss():
    print("---------------------------------")
    print(f"                               Player 1")
    print("                                0")
    print("_________________M________________")
    print("0                M               ")
    print(f"Player 2")
    print("---------------------------------")
def both_players_unseated(): 
    print("---------------------------------")
    print(f"             Player 1")
    print("                                 ")
    print("_________________X________________")
    print("                 X               ")
    print(f"             Player 2")
    print("---------------------------------")
def P1_unseats_P2_Hits(): 
    print("---------------------------------")
    print(f"                               Player 1")
    print("                                0")
    print("_________________H________________")
    print("                 X               ")
    print(f"            Player 2")
    print("---------------------------------")
def P2_unseats_P1_Hits():
    print("---------------------------------")
    print(f"             Player 1")
    print("                                 ")
    print("_________________X________________")
    print("0                H               ")
    print(f"Player 2")
    print("---------------------------------")
#Player 1 Unseats. Player 2 missed 9
def P1_Unseats_P2_Misses():
    print("---------------------------------")
    print(f"                               Player 1")
    print("                                0")
    print("_________________M________________")
    print("                 X               ")
    print(f"            Player 2")
    print("---------------------------------")
def P2_Unseats_P1_Misses():
    print("---------------------------------")
    print(f"             Player 1")
    print("                                ")
    print("_________________X________________")
    print("0                M               ")
    print(f"Player 2")
    print("---------------------------------")

