    #Module for the READ me and RULES
import mysql.connector
def rules_intro():
    print()
    print("                             ---------------------------------INTRODUCTION----------------------------------")
    print("                                  This game inspired by the table top RPG game Dungeons and Dragons (DnD).")
    print()
    print("        This is a virtual version of a mini-game where two opponents joust each other on horse back and roll dice to determine the outcome.")
    print("                     The goal of this game is to build your character and influence your dice rolls to beat your opponent in the joust.")
    print()
    print()
    print("----CHARACER CREATION----")
    print("The important Statistics for this game are your Attack, Defense, Damage, and Animal Handling.")
    print()
    print("ATTACK - You want this to be higher than your opponents defense so you can score a hit.")
    print("DEFENSE- You want this statistic to be higher than your opponents attack so you don’t get hit. ")
    print("DAMAGE- You want to roll this as high as possible. The higher the damage the better chance you can un-seat your opponent and win the match.")
    print("ANIMAL HANDLING - This statistic is used for your brace check which is used against your opponent’s damage roll.")                          
    print("                  You want this number higher than your opponent's damage so you stay on your horse and not potentially lose the joust. ")
    print()
    print()
def rules_how_to_play():
    print("________________________Once the players build their characters and are given their player stats they are ready to joust!________________________")
    print()
    print("----HOW THE GAME WORKS----")
    print("Both players charge at and past each other from opposite ends of the arena.")
    print("Players choose their attack stance before they roll.")
    print("The attack stance give major bonuses/reductions to a players roll which will alter the outcome of the joust.")
    print()
def game_mechanics():
    print("---HOW THE GAME WORKS---")
    print()
    print("After players choose their attack stance for the round:\n1. Players will roll an attack- They will roll a D20 die. (Simulated with the random module")
    print("2. Attack rolls will be compared against the opposing players defense.\n3. Attacks happen simultaneously, and it is possible for two jousters to unseat each other at the same time.")
    print()
    print("---SCORING A HIT---")
    print()
    print("If the player scores a hit (Their attack roll is higher than their opponents defense) they will get 1 point.\n They will also roll for damage against the opponent and attempt to unseat them for the win.")
    print("Both players have a shield and lance. A D12 die is used to determine damage and they will be give a +3 to the damage modifier. The Random Module simulates the dice roll")
    print("If a player is hit they must make a brace check to prevent being unseated.\n They will roll a D20 and apply their animal handling modifier to prevent being unseated.")
    print("If a players animal handling check fails against their opponents damage roll, the opposing player will score three points and the match will end. ")
    print()
    print()
    print("--A winner is the first to three points or highest score in the event both riders are unseated at the same time---")
    print()
    print()
    print("------SCORING-------")
    print()
    print("1 point if hit (break lance) your opponent during a pass but they are not knocked off.\n3 points and match ends if opponents falls off their horse (unseated).")
    print()
    print()
    print("-----PLAYER POSITIONS-----")
    print('These are simple text graphics that allow the players to see where they are on the field and indicators for when they score a hit/miss unseat')
    print()
    print("Example---- This is the players starting positions")
    print("---------------------------------")
    print(f"Player 1") 
    print("0                                ")
    print("_________________________________")
    print("                                0")
    print(f"                                Player 2")
    print("---------------------------------")
    print(f"""Player 1 is on the left. The 0 indicates their "horse" and position on the field. Player 2 is on the right indicated with a 0""")
    print()
    print()
    print(f"As the players roll their attacks their positions on the field will change")
    print(f"Example of a Player Getting hit:")
    print()
    print(f"Player 1 scores a hit against player 2 and Player 2 misses their attack")
    print("---------------------------------")
    print(f"                              Player 1")
    print("                                0")
    print("_________________M________________")
    print("0                H               ")
    print(f"Player 2")
    print("---------------------------------")
    print(f"As you can see the players have moved. M indicates the player was missed, H indicates the player was hit. When you see an  X, it indicates the player was unseated.")

